# Header
menu:
  APPS:
    Android Apps:
      google: //google.com/
      yahoo:  //yahoo.com/
    iOS Apps:
      google: //google.com/
      yahoo:  //yahoo.com/

extmenu:
  github: //github.com/geesun/
#  theme:
#    biture: //github.com/kywk/hexo-theme-biture
#    landscape: //github.com/tommy351/hexo-theme-landscape
#    light: //github.com/tommy351/hexo-theme-light

# Content
excerpt_link: Read More

fancybox: false 

# Miscellaneous
google_analytics:
rss:
